export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const SAVE_ORDER = 'SAVE_ORDER';
export const FAILED_CALL = 'FAILED_CALL';
export const LOADING = 'LOADING';
